<a href="https://colab.research.google.com/github/alifrain/Data-Mining/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[['France' 50.0 36000.0]
 ['Spain' nan 41000.0]
 ['Germany' 30.0 60000.0]
 ['Spain' 38.0 61000.0]
 ['Argentina' 30.0 nan]
 ['France' 35.0 58000.0]
 ['Portugal' 21.0 52000.0]
 ['Netherlands' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [11]:
print(x)

[['France' 50.0 36000.0]
 ['Spain' 37.666666666666664 41000.0]
 ['Germany' 30.0 60000.0]
 ['Spain' 38.0 61000.0]
 ['Argentina' 30.0 59666.666666666664]
 ['France' 35.0 58000.0]
 ['Portugal' 21.0 52000.0]
 ['Netherlands' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encider', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 50.0 36000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 37.666666666666664 41000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 30.0 60000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 30.0 59666.666666666664]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 21.0 52000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [18]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 21.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 30.0 59666.666666666664]
 [0.0 1.0 0.0 0.0 0.0 0.0 50.0 36000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 37.666666666666664 41000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 30.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


In [20]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [21]:
print(y_test)

[0 1]


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [23]:
print(x_train)

[[0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 -0.5773502691896258
  -1.833686004594795 -0.4372820977874461]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.901742058730146 0.062468871112492504]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  1.1692444876357406 -1.4802406415786227]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.7320508075688774
  -0.07334744018379133 0.1493820830950907]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.7320508075688774
  -0.10786388262322302 -1.15431609664388]
 [0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 -0.5773502691896258
  0.962145832999152 1.3227104448601643]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  1.1692444876357406 1.5834500808079586]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.3839954221386743 -0.0461726438657549]]


In [24]:
print(x_test)

[[0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.901742058730146 0.08419717410814218]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.17689676750208566 0.5404915370167819]]
